### PR TITLE
Add OEDGE documentation to master and merge in diiid-shawn

### PR DESCRIPTION
**Pull request by shawnzamperini**
- Most of the commits are from the documentation. I had to commit every time I wanted to recompile the website, so it's a lot of commits. 
- I removed SOL29 code from the repository. I think I based on faulty/incomplete assumptions and would prefer it not be included.
- I modified the "blob" model to instead consider fluctuations in the poloidal electric field. Conceptually it is the same idea but is more general and relies on less assumptions. Model is tested and in draft of paper under review at time of this writing.
- master has been merged into diiid-shawn.
- Couple other tiny bug fixes sprinkled in with the necessary details in the accompanying comments.
- All testcases have been tested as well as some extended grid cases of my own. 

With the documentation, it currently points the website from the files in diiid-shawn. Once they are pushed to master I can update it to use those files instead, then it can be modified and added to like any other file.

### CODE REVIEW

**Review by jdelder — COMMENTED** [review]
Some comments. 
In mod_unstructured_input.f90
1) use grdmod = 0.0 instead of the loops - fixed loops is bad when arrays are dynamically allocated. 
This means you don't need to know the size of the array and you don't need either the loops or the loop variables.
2) I think grdnmod should default to zero. grdnmod is the number of grid modifications and I believe it triggers code to do "manual" grid edits. However, it is possible that some part of Steve's code is triggered by grdnmod being non-zero and that code is required for his extended grids ... this probably needs a bit more debugging to determine what is going on exactly for grdnmod (It is possible that grdnmod only matters when extended grids are read but I'm not confident. If grdnmod is needed for extended grids then we should initialize grdnmod to 0 and pick an appropriate place to set grdnmod = 1. This would likely be at the start of the code that reads unstructured grids (I think it is at the start of the raug routine where it reads a tag in the grid file and uses that to figure out which routine to read the file with). So grdnmod=1 could be set as soon as the code knows it is dealing with an extended grid. It should not matter prior to that. 
The problem with grdnmod=1 as default is that it may incorrectly trigger some of Steve's code for any type of mesh. (I recall having some issues with test cases with grdnmod=1 for regular grids - but I don't recall the specific issue.

3) I am not reviewing the documentation specifically since I think there is too much to be added to it still. I consider it a work in progress addition to the code and it should not have any impact on code execution by other users. 

That is basically all that I saw after going through the code. However, I also did not review the python changes to the plotting code. Some of those appeared to be type conversions of variables read from the NC file while others appeared to be a bit more extensive (mapping LP data to the mesh for example). I'm assuming you have tested those updates. 

P.S. If it isn't there already .. can you include a README on how to add to and update the documentation. Ideally, developers would add any new features to the documentation themselves but they would need to know the process and how to easily add documentation for their new options or features.

**Comment by shawnzamperini** [comment]
I moved the grdnmod fix to tau.f in the section where the ReadGeneralizedGrid_OSM code gets called, so it shouldn't have an effect for standard grids. All testcases and my extended grid runs execute as normal.

I also added a README.md to the docs file with some info about the ReadTheDocs process. 

The python plotting code was added/updated for the Beginner's Guide, so I can say it works for the example in that at least.

**Comment by jdelder** [comment]
Ok. The changes for grdnmod look fine. Looking over the changes, I noted that you changed run_testcases.iris back to the usual format for the rundiv command. It looks like you had a different order for the arguments to rundiv? The Read the Docs README looks like a good starting point for anyone wanting to add to the documentation. 

However, one feature of the documentation that I've found very useful is the DIVIMP input file with cross references - basically HTML links to the old documentation for each line of the input file. Will the Read the Docs format support that? An input file or similar structure with each tag pointing to the documentation for that tag? I'm not sure if it will really be needed if all the tags are listed in alphabetical order since the order of inputs in the file no longer matters but it was a feature I found useful. Another application of that feature is in the python input file display/edit features in OMFIT. I was thinking of taking that out of OMFIT and implementing it as a standalone or as part of an OEDGE python suite that could include both input and output processing. In which case, being able to link directly to documentation from an input file tag would be very useful.

**Comment by shawnzamperini** [comment]
Originally my batch submit file had a different order than the normal rundiv.iris order. This was just for personal convenience when I initially made the script. For example, I never used the <CFD solution> option so I had it always set to none in the batch script. This clearly is not a good idea for the general user who may need those files, so I changed the batch script to use the same syntax as rundiv.iris. Should've done it awhile ago! 

With the documentation, essentially anything is possible. The functionality you are describing can certainly be done. I just tested it on the following page in the first code block (for input option S21):

https://oedge.readthedocs.io/en/latest/beginner_osm.html 

We could add a section to the documentation called something like "Example Input Files", and each page has the input file with the links as you describe and shown above. It would also be a good idea to briefly describe on these pages what the input file was used for and, if possible, the publication it showed up in. The Gkeyll group does something similar and I've found already found it very useful. We could start with your input files used for the C13 puffing if you still have them, Jake's on the MRC drifts, mine with SiC walls. The more the merrier I'd say, we can always subcategorize them if they get too numerous to list en masse.

**Comment by jdelder** [comment]
I meant to approve this last week but forgot. Oops. I should also mention that there is a divimp-data-files repo where I have stored most of the input files that have been used for divimp and lim over the years going back to div3 I think. We could add that to the ORNL repo as well. I also have the fuse repository with Steve's IDL code if you think it is worth adding that to either the ORNL repo as a separate entity or as part of the divimp repo.

**Review by jdelder — APPROVED** [review]
I've looked through the code a few times and any issues have already been addressed.

**Pull request merged**
