### PR TITLE
Merge diiid-shawn into master

### PR DESCRIPTION
**Pull request by shawnzamperini**

### CODE REVIEW

**Comment by jdelder** [comment]
Hi Shawn - comments and change requests :)

1) mod_solcommon.f90 is a SOL22 internal common module. It should really be called mod_sol22common but solcommon was used for historical reasons when the code was switched from common blocks to modules. Blobby transport variables should be put somewhere else - maybe in a module dedicated to blobby transport?

2)  The best place to declare the variables you read in with the mod_sol29_input.f90 module is possibly at the beginning of that module. Alternatively, you could group the declarations and code into a mod_sol29_data module that includes the declaration, allocation, unstructured read routines. You shouldn't be using mod_solcommon for your new variables since mod_solcommon is also used in the SOL22 standalone solver and in the LIM sol22 solver. If you declare them at the beginning of the input module, you won't need the import mod_solcommon reducing the code interdependency. It also keeps the option specific code and data together which is also a good idea. I like to group the variable creation/manipulation code in one module and the code that actually does the work in a second module (but I clearly haven't been that consistent with it unfortunately - partly because the migration to fortran 90 is an ongoing process).

3) I would move the allocate_mod_solcommon29 code as well as the declarations from mod_solcommon to mod_sol29_input - then use the mod_sol29_input module when you need to access these variables. I don't think any of your code should need to access anything in solcommon that was already there.

4) mod_eirene06 - just wondering why the max_strata was increased to 500 from 100? My understanding was that there were typically only three strata of neutrals launched in EIRENE. Looking at some of the eirout files from OEDGE Eirene runs the number of stata is reported as 3. 

Sample input files usually list the stata that are defined - eg

$Type  NPTS    Flux     Frac  Spe  Ind  E(eV)   TARGET  IND1  2                             Note
$-----------------------------------------------------------------------------------------------
 1.0   -90000  1.0      1.0   4    1    0.0     1                                           'inner target'
 1.0   -90000  1.0      1.0   4    1    0.0     2                                           'outer target'
 2.0   -90000  1.0      1.0   4    1    0.0                                                 'volume recombination'
$                                               COS MAX   POSX   Y     Z    VECX  Y    Z         
$                                               ------------------------------------------      
$ 3.0    -90000  1.0E+3    1.0   2    1    0.038  1.0 90.0  1.41  -1.346   0.0  1.0   0.0  0.0  'duct puff'
$
$ 3.0    -90000  1.0E+3    1.0   2    1    0.038  1.0 90.0  2.353  0.0    0.0   1.0   0.0  0.0  'omp puff'
$ 3.0    -90000  1.0E+3    1.0   2    1    0.038  1.0 90.0   1.02  0.0    0.0  -1.0   0.0  0.0  'imp puff'
$ 3.0    -90000  1.0E+3    1.0   2    1    0.038  1.0 90.0   1.3   1.3    0.0   0.0   1.0  0.0  'top puff'
$ 3.0    -90000  1.0E+3    1.0   2    1    0.038  1.0 90.0  1.35  -1.365  0.0   0.0  -1.0  0.0  'pfz puff'
$                                               ------------------------------------------      

This case is 3 strata - inner target, outer target and volume recombination. Additional strata could be puffs. I guess I am missing why this needed to be increased to 500 from 100.


5) I'm trying to figure out why you made the following change in eirene06.f ... was there an issue when you were running the code? Which version of EIRENE was affected?
! The associated EIRENE format string for this line when read in
! is 12(5L1,5X), so it has the capacity to read in 12 * 5 = 60
! strata. This below hardcodes 14 for some reason. We should at
! least allow for the maximum number, so I use the repeat
! function to write 12 sets of 5 T's. Tested with gcc.
! sazmod

The string when read in is actually 12(5L1,1X) not 5X which is 12 blocks of logical variables of length 1 each with 5 variables listed followed by a space.

You changed the existing code that wrote 14 T's to write 60 T's instead because the format string on the Eirene side could read 60 T's. However, that is irrelevant. What matters is how many variables the corresponding input on the EIRENE side was actually reading. (Note that this is all in block 11 which controls the EIRENE output that could be read in by OEDGE/OSM routines).

In eirene99, this line is read into a variable that goes as high as the number of strata. However, in eirene07 which is the version most often used, I am not sure that the line gets used at all. (The EIRENE input file format is among the worst I have ever encountered to be honest). On the other hand, the number of strata is usually low ... did this cause a problem in a case you were running?

If neither of these eirene related changes were not related to a bug, could I get you to undo them? I don't think EIRENE could even support 500 strata? However, I would need to do a lot more digging to see what is working and what isn't. Steve did most of the EIRENE interface code a long time ago as part of his thesis.

6) Adding another smoothing option to SOL22 is fine.

I just tend to warn against using smoothing options. It is important to remember that smoothed plasmas look nicer but they are strictly unphysical. They aren't a real solution. The reason for the discontinuity at the midplane is physics. A combination of mismatched inner and outer target conditions due to diagnostic uncertainties in both magnitude and particularly location combined with missing physics terms in the solver are the likely reason for the discontinuity. Smoothing makes it look cool but hides away that the resulting solution doesn't have much meaning. Also, the divertor solutions from the OSM are typically the most accurate so I would tend to suggest keeping smoothing adjustments above the Xpoint rather than going all the way down to the targets but as long as it is documented it isn't an issue.

7) In tau.f
! confusion in the different types of unstructured inputs makes
! me feel safer to just check for cdperpc = -1.0 here.
if (cdperpc.lt.0) then
cdperpc = cdperp
endif
! sazmod - Ideally this would be done in divinput, but the

You should move this to the end of the READIN routine in divinput.f. By the end of READIN, the entire input file will have been processed including unstructured inputs. So the best place for this sort of check and assignment is with the other similar input checking code at the end of READIN.

8) You shouldn't have to update the .gitignore file to ignore individual local files you create since those updates to .gitignore get propagated to everyone else and if they have a sputter_old.f file then it ends up getting permanently ignored too. If you have a file you want to still keep around for a while but which isn't a part of the repo then it is probably better to copy it to a local backup directory for later reference.

9) A bunch of SiC code was added. Has this been tested for a range of cases? What is the correct sputter option needed to turn it on? It looks like it might be sputter option 8.

10) In ion_crossfield_transport.f - does your blobby transport option replace the existing vr_pdf code? Or is it another option that can be selected? It is hard to tell from looking at the code diffs in github but it looks like the existing code was replaced which I would prefer to avoid since there are existing inputs and other code that stops working entirely if the existing option is removed. However, it could just be the diffs I am looking at ...

11) Perhaps another problem reading a diff ... ion_transport.f

The call to do_parallel_transport was replaced with the following:
! assumes impurities get caught up in blobs and that the blobs
! ballistically transport radially, shielding the impurity from
! the surrounding plasma (and thus the external forces).
if (in_blob_switch.and.(.not.in_blob)) then
call do_parallel_step(seed, nrand, neutim, spara, dspara, vpara,
> dvpara)
endif
! sazmod - Only execute the parallel step if not in a blob. This

What happens for cases not using the blob model? If in_blob_switch is false, the parallel transport step never gets executed? I think this if statement is missing an else to execute the parallel transport step for every other case ...?

Also, looking at the code in unstructured_input.f, it looks like in_blob_switch is an integer with a default value of 0. Using an IF statement like if (in_blob_switch ... for an integer assumes that every compiler shares the meaning of true and false so that a value of 0 is considered true. It is best to avoid using integers as logicals though the compiler won't necessarily complain about it.

So I think there are a couple of possible bugs to fix with the invocation of the blob transport.

--

**Comment by shawnzamperini** [comment]
1. Moved SOL29 input to mod_sol29_input.f90. 

2. Addressed above. 

3. Addressed above. 

4. Changed back down to 100.  

5. The change is apparently needed if you have more than 14 point sources in EIRENE. I did a case with more than 14 point source "puffs" to simulate wall outgassing, and found that the number of logicals printed out to the EIRENE input file needed to be increased. I increased it to 60 as that is the max values indicated in the EIRENE documentation (as you mentioned). Curiously enough, I still can't go past 35 point source before hitting an error, so other issues seem to remain.  

7. Understood.  

8. Done. 

9. Done. 

10. The SiC code has been tested as a single wall element of SiC as well as the entire wall as SiC for a LSN DIII-D L-Mode (#167196). There is no experimental evidence to benchmark the results against, but comparing to identical runs where the walls were specified to be graphite showed reasonable looking comparisons (e.g., lower overall Zeff with SiC compared to graphite). I've also spent time using the same code in 3DLIM for similar studies. I think it's implemented correctly.  

I included documentation for them in unstructured_input_com.f since it seem like that's the best source of documentation for input options not on the DIVIMP website.  
```
!     TAG D41-43 
!     These options are related to sputtering from SiC using the SiC  
!     mixed-material model in Abrams NF 2022. Note this requires  
!     csputopt = 8. 
!     D41: Usage switch. Useful for comparisons of SiC to its  
!          constituents using the same yield data that is hardocded in  
!          for SiC. 
!          1 = Normal. Target is SiC. 
!          2 = Target is graphite. 
!          3 = Target is silicon. 
!     D42: Flux fraction of the carbon in the incoming plasma flux. 
!     D43: Flux fraction of the silicon in the incoming plasma flux. 
```
Note I intend to add a future upgrade to that that would remove input options D42 and D43, the fraction of C and Si impinging on the SiC for the needed yield calculations, since the SiC mixed-material equations can be self-consistently solved (8 equations, 8 unknowns), but I need to figure out how to do this in Fortran.  

11. Technically, the code does replace the previous vr-pdf code, but not really. The previous code is used whenever and ion is determined in a blob. So you can recover the previous behavior by setting the blob frequency to an arbitrarily large value so that it immediately samples from the input vr-pdf. Specifically: 

T49 = 1e30  # Arbitrarily large number 
T54 = 0        # No ballooning approximation. 
T56 = 0        # Yes parallel transport when in blob 

I changed the default value for fblob to be 1e30. The others are already set to the above by default, so old input files with vr-pdf *should* output the same results. I don't have an old input file to confirm this though. 

The correlation time (T30) is the same as before, I didn't mess with that. There are a couple minor changes though that are permanent in the current code: 

- vr-pdf is only applied when `ir.gt.irsep`. It has no effect in the core, this makes more physical sense to me. 
- cvpinch (T16) can be used as an additional value on top of vr-pdf. Effectively shifts the entire vr-pdf by cvpinch.  

12. That may be the diff not showing everything. The blob model only kicks in when `npdf_data.gt.0`. If there is nothing input then the parallel transport is done like normal: 
```
! sazmod - Only execute the parallel step if not in a blob. This
! assumes impurities get caught up in blobs and that the blobs 
! ballistically transport radially, shielding the impurity from
! the surrounding plasma (and thus the external forces). This only
! applies if the pdf was supplied, so we check that by seeing if
! npdf_data > 0. 
if (npdf_data.gt.0) then
  if (in_blob_switch.eq.1) then
    if (.not.in_blob) then
      call do_parallel_step(seed, nrand, neutim, spara, dspara, 
>        vpara, dvpara)
    endif
  else
    call do_parallel_step(seed, nrand, neutim, spara, dspara, 
>      vpara, dvpara)
  endif
else
  call do_parallel_step(seed, nrand, neutim, spara, dspara, 
>    vpara, dvpara)
endif
```

**Comment by jdelder** [comment]
Looks good :)

**Review by jdelder — APPROVED** [review]
Looks good ... just trying to figure out the process ...

**Pull request merged**
